version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    environment:
      GITHUB_USERNAME: "yashwagh30"
      GITHUB_TOKEN: "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"  # Use ENV variable securely in practice
      DOCKER_USERNAME: "yashwagh30"
      DOCKER_PASSWORD: "Y@shdocker30"
    steps:
      - setup_remote_docker

      - checkout

      - run:
          name: Show GitHub Token (for testing only)
          command: |
            echo "GitHub Username: $GITHUB_USERNAME"
            echo "GitHub Token: $GITHUB_TOKEN"

      - run:
          name: Clone a Repo using GitHub Token
          command: |
            git clone https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/CircleCI-Docker.git

      - run:
          name: Docker Build
          command: |
            docker --version
            docker build -t $DOCKER_USERNAME/circleci-demo:latest .

      - run:
          name: Docker Login and Push
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $DOCKER_USERNAME/circleci-demo:latest

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
